function [idxValidSat, validSat, nSV] = makeSvIndexEpoch(trial,pseudorangeEpoch)
    %%% Valid satellite data
    validSat = ...
        all(isfinite(pseudorangeEpoch)) & ...
        isfinite(trial.gnss.satellitePosition(1,:)).' & ...
        isfinite(trial.gnss.satellitePosition(2,:)).' & ...
        isfinite(trial.gnss.satellitePosition(3,:)).';

    idxValidSat = find(validSat);
    nSV = length( idxValidSat );
end