function [idxValidSat, validSat, nSV] = makeSvIndexEpoch(satellitePosition,pseudorangeEpoch)
    %%% Valid satellite data
    validSat = ...
        all(isfinite(pseudorangeEpoch)) & ...
        isfinite(satellitePosition(1,:)).' & ...
        isfinite(satellitePosition(2,:)).' & ...
        isfinite(satellitePosition(3,:)).';

    idxValidSat = find(validSat);
    nSV = length( idxValidSat );
end