function profiles = mergeOutliersProfiles(userProfiles)

    nFaults = numel(userProfiles);

    template = struct( ...
        'type','measurement_bias', ...
        'startTime',0, ...
        'endTime',inf, ...
        'seed',[], ...
        'frequencies','all', ...
        'observation','both', ...
        'mode','explicit', ...
        'satIDs',[], ...
        'constellations',{{}}, ...
        'nSat',[], ...
        'nSatPerConstellation',[], ...
        'reuseFault',[], ...
        'magnitudeType','constant', ...
        'magnitudeValue',0, ...
        'magnitudeInitialValue',0, ...
        'magnitudeSlope',0, ...
        'magnitudeMean',0, ...
        'magnitudeStd',1, ...
        'magnitudeSigma',1, ...
        'magnitudeDirection',[1 0 0]); % Optional vector direction for ephemeris fault

    profiles = repmat(template,1,nFaults);

    for j = 1:nFaults

        names = fieldnames(userProfiles(j));

        for i = 1:numel(names)
            name = names{i};
            profiles(j).(name) = userProfiles(j).(name);
        end

    end
end